version: '3.5'
services:
  tracker:
    build: ./fastdfs
    image: lyb/fastdfs
    container_name: tracker
    restart: always
    hostname: tracker
    command: sh tracker.sh
    ports:
      - 22122:22122
  storage:
    image: lyb/fastdfs
    container_name: storage
    restart: always
    hostname: storage
    ports:
      - 23000:23000
      - 8888:8888
    volumes:
      - ../fastdfs/data:/data/fast_data/data
      - ../fastdfs/nginx/nginx.conf:/etc/nginx/conf/nginx.conf
    environment:
      - TRACKER_IP=tracker:22122
      - GROUP_NAME=group1
    depends_on:
      - tracker
    command: sh storage.sh
networks:
  default:
    name: fastdfs_net

